schema = 3

[mod]
  [mod."github.com/adrg/xdg"]
    version = "v0.4.0"
    hash = "sha256-zGjkdUQmrVqD6rMO9oDY+TeJCpuqnHyvkPCaXDlac/U="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20211025201205-69cdffdb9359"
    hash = "sha256-GE8ysfcBR4XoK0X9vmu6PVEQmnTCe5+GY9zUAF223L8="
